
import java.awt.CardLayout;
import java.awt.LayoutManager;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Seán
 */
public class bioPanel extends javax.swing.JPanel {

    /**
     * Creates new form bioPanel
     */
    public bioPanel() {
        initComponents();
        //Back Icon changes on hover
        backBtn.setRolloverIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
        backBtn.setSelectedIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
        
        //Check Icon changes on hover
        confirmBtn.setRolloverIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\CheckBtnHoverPressed.png"));
        confirmBtn.setSelectedIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\CheckBtnHoverPressed.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        HumanBioTitle = new javax.swing.JLabel();
        PlantAnatomyTitle = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        skelOption = new javax.swing.JRadioButton();
        RespOption = new javax.swing.JRadioButton();
        CircOption = new javax.swing.JRadioButton();
        PhotoOption = new javax.swing.JRadioButton();
        PlantOption = new javax.swing.JRadioButton();
        VegOption = new javax.swing.JRadioButton();
        background = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 600));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HumanBioTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        HumanBioTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/HumanBioTitle.png"))); // NOI18N
        jPanel1.add(HumanBioTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        PlantAnatomyTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        PlantAnatomyTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/PlantAnatomyTitle.png"))); // NOI18N
        jPanel1.add(PlantAnatomyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, 70));

        confirmBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/CheckBtnDefault.png"))); // NOI18N
        confirmBtn.setContentAreaFilled(false);
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });
        jPanel1.add(confirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 100, 80));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/BackBtnDefault.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 100, 80));

        buttonGroup1.add(skelOption);
        skelOption.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 20)); // NOI18N
        skelOption.setForeground(new java.awt.Color(255, 255, 255));
        skelOption.setText("Skeleton & Muscles");
        skelOption.setContentAreaFilled(false);
        skelOption.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/skull.png"))); // NOI18N
        skelOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skelOptionActionPerformed(evt);
            }
        });
        jPanel1.add(skelOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 210, -1));

        buttonGroup1.add(RespOption);
        RespOption.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 20)); // NOI18N
        RespOption.setForeground(new java.awt.Color(255, 255, 255));
        RespOption.setText("Respiratory System");
        RespOption.setContentAreaFilled(false);
        RespOption.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/lungs.png"))); // NOI18N
        jPanel1.add(RespOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 200, -1));

        buttonGroup1.add(CircOption);
        CircOption.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 20)); // NOI18N
        CircOption.setForeground(new java.awt.Color(255, 255, 255));
        CircOption.setText("Circulatory System");
        CircOption.setContentAreaFilled(false);
        CircOption.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/heart.png"))); // NOI18N
        jPanel1.add(CircOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 220, -1));

        buttonGroup1.add(PhotoOption);
        PhotoOption.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        PhotoOption.setForeground(new java.awt.Color(255, 255, 255));
        PhotoOption.setText("Photosynthesis");
        PhotoOption.setContentAreaFilled(false);
        jPanel1.add(PhotoOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 161, -1));

        buttonGroup1.add(PlantOption);
        PlantOption.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        PlantOption.setForeground(new java.awt.Color(255, 255, 255));
        PlantOption.setText("Plant Structure");
        PlantOption.setContentAreaFilled(false);
        PlantOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlantOptionActionPerformed(evt);
            }
        });
        jPanel1.add(PlantOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        buttonGroup1.add(VegOption);
        VegOption.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        VegOption.setForeground(new java.awt.Color(255, 255, 255));
        VegOption.setText("Vegetative Propagation");
        VegOption.setContentAreaFilled(false);
        jPanel1.add(VegOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/Background.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        if (skelOption.isSelected()) {
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof CardLayout) {
                CardLayout cl = (CardLayout) layout;
                cl.show(getParent(), "skeleton");
            }
        }
        if (PhotoOption.isSelected()) {
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof CardLayout) {
                CardLayout cl = (CardLayout) layout;
                cl.show(getParent(), "photosynthesis");
            }
        }
        if (VegOption.isSelected()) {
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof CardLayout) {
                CardLayout cl = (CardLayout) layout;
                cl.show(getParent(), "vegetative");
            }
        }
         if (PlantOption.isSelected()) {
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof CardLayout) {
                CardLayout cl = (CardLayout) layout;
                cl.show(getParent(), "plant");
            }
        }
        if (RespOption.isSelected()) {
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof CardLayout) {
                CardLayout cl = (CardLayout) layout;
                cl.show(getParent(), "respiratory");
            }
        }
        if (CircOption.isSelected()) {
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof CardLayout) {
                CardLayout cl = (CardLayout) layout;
                cl.show(getParent(), "circulatory");
            }
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "home");
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void skelOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skelOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skelOptionActionPerformed

    private void PlantOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlantOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlantOptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CircOption;
    private javax.swing.JLabel HumanBioTitle;
    private javax.swing.JRadioButton PhotoOption;
    private javax.swing.JLabel PlantAnatomyTitle;
    private javax.swing.JRadioButton PlantOption;
    private javax.swing.JRadioButton RespOption;
    private javax.swing.JRadioButton VegOption;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton skelOption;
    // End of variables declaration//GEN-END:variables
}
