
import java.awt.CardLayout;
import java.awt.LayoutManager;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Renalyn
 */
public class circPanel extends javax.swing.JPanel {

    /**
     * Creates new form circPanel
     */
    public circPanel() {
        initComponents();
        arteriesImg.setVisible(false);
        arteriolesImg.setVisible(false);
        capillariesImg.setVisible(false);
        venulesImg.setVisible(false);
        veinsImg.setVisible(false);
        
        //Back Icon changes on hover
        backBtn.setRolloverIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
        backBtn.setSelectedIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        veinsImg = new javax.swing.JLabel();
        venulesImg = new javax.swing.JLabel();
        capillariesImg = new javax.swing.JLabel();
        arteriolesImg = new javax.swing.JLabel();
        arteriesImg = new javax.swing.JLabel();
        circLbl = new javax.swing.JLabel();
        diagram1 = new javax.swing.JButton();
        diagram2 = new javax.swing.JButton();
        diagram3 = new javax.swing.JButton();
        diagram4 = new javax.swing.JButton();
        diagram5 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        veinsImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/fc5.png"))); // NOI18N
        add(veinsImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        venulesImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/fc4.png"))); // NOI18N
        add(venulesImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 320, 200));

        capillariesImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/fc3.png"))); // NOI18N
        add(capillariesImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        arteriolesImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/fc2.png"))); // NOI18N
        add(arteriolesImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        arteriesImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/fc1.png"))); // NOI18N
        add(arteriesImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        circLbl.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        circLbl.setText("Circulatory System");
        add(circLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        diagram1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/num1.png"))); // NOI18N
        diagram1.setContentAreaFilled(false);
        diagram1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagram1ActionPerformed(evt);
            }
        });
        add(diagram1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 40, -1));

        diagram2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/num3.png"))); // NOI18N
        diagram2.setContentAreaFilled(false);
        diagram2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagram2ActionPerformed(evt);
            }
        });
        add(diagram2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 40, -1));

        diagram3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/num4.png"))); // NOI18N
        diagram3.setContentAreaFilled(false);
        diagram3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagram3ActionPerformed(evt);
            }
        });
        add(diagram3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 40, -1));

        diagram4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/num5.png"))); // NOI18N
        diagram4.setContentAreaFilled(false);
        diagram4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagram4ActionPerformed(evt);
            }
        });
        add(diagram4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 40, -1));

        diagram5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/num2.png"))); // NOI18N
        diagram5.setContentAreaFilled(false);
        diagram5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagram5ActionPerformed(evt);
            }
        });
        add(diagram5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 40, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/BackBtnDefault.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 100, 80));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/bioBg.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void diagram1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagram1ActionPerformed
        arteriesImg.setVisible(true);
        arteriolesImg.setVisible(false);
        capillariesImg.setVisible(false);
        venulesImg.setVisible(false);
        veinsImg.setVisible(false);
    }//GEN-LAST:event_diagram1ActionPerformed

    private void diagram2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagram2ActionPerformed
        arteriesImg.setVisible(true);
        arteriolesImg.setVisible(true);
        capillariesImg.setVisible(true);
        venulesImg.setVisible(false);
        veinsImg.setVisible(false);
    }//GEN-LAST:event_diagram2ActionPerformed

    private void diagram3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagram3ActionPerformed
        arteriesImg.setVisible(true);
        arteriolesImg.setVisible(true);
        capillariesImg.setVisible(true);
        venulesImg.setVisible(true);
        veinsImg.setVisible(false);
    }//GEN-LAST:event_diagram3ActionPerformed

    private void diagram4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagram4ActionPerformed
        arteriesImg.setVisible(true);
        arteriolesImg.setVisible(true);
        capillariesImg.setVisible(true);
        venulesImg.setVisible(true);
        veinsImg.setVisible(true);
    }//GEN-LAST:event_diagram4ActionPerformed

    private void diagram5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagram5ActionPerformed
        arteriesImg.setVisible(true);
        arteriolesImg.setVisible(true);
        capillariesImg.setVisible(false);
        venulesImg.setVisible(false);
        veinsImg.setVisible(false);
    }//GEN-LAST:event_diagram5ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "biology");
        }
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arteriesImg;
    private javax.swing.JLabel arteriolesImg;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel background;
    private javax.swing.JLabel capillariesImg;
    private javax.swing.JLabel circLbl;
    private javax.swing.JButton diagram1;
    private javax.swing.JButton diagram2;
    private javax.swing.JButton diagram3;
    private javax.swing.JButton diagram4;
    private javax.swing.JButton diagram5;
    private javax.swing.JLabel veinsImg;
    private javax.swing.JLabel venulesImg;
    // End of variables declaration//GEN-END:variables
}
