
import java.awt.CardLayout;
import java.awt.LayoutManager;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Renalyn
 */
public class combPanel extends javax.swing.JPanel {

    /**
     * Creates new form combPanel
     */
    public combPanel() {
        initComponents();
        //Back Icon changes on hover
        backBtn.setRolloverIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
        backBtn.setSelectedIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
        
        DefinitionBtn.setRolloverIcon(new ImageIcon("GUIImages\\Statistic\\DefinitionBtnHover.png"));
        DefinitionBtn.setSelectedIcon(new ImageIcon("GUIImages\\Statistic\\DefinitionBtnHover.png"));
        
        ExamplesBtn.setRolloverIcon(new ImageIcon("GUIImages\\Statistic\\ExampleBtnHovered.png"));
        ExamplesBtn.setSelectedIcon(new ImageIcon("GUIImages\\Statistic\\ExampleBtnHovered.png"));
        
        ExerciseBtn.setRolloverIcon(new ImageIcon("GUIImages\\Statistic\\ExerciseBtnHovered.png"));
        ExerciseBtn.setSelectedIcon(new ImageIcon("GUIImages\\Statistic\\ExerciseBtnHovered.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        DescriptiveStatistic = new javax.swing.JLabel();
        DefinitionBtn = new javax.swing.JButton();
        ExamplesBtn = new javax.swing.JButton();
        ExerciseBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 600));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/BackBtnDefault.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DescriptiveStatistic.setBackground(new java.awt.Color(102, 51, 255));
        DescriptiveStatistic.setFont(new java.awt.Font("Tekton Pro", 0, 44)); // NOI18N
        DescriptiveStatistic.setForeground(new java.awt.Color(153, 0, 204));
        DescriptiveStatistic.setText("Comb&Permut");
        jPanel1.add(DescriptiveStatistic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        DefinitionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DefinitionBtnDefault.png"))); // NOI18N
        DefinitionBtn.setContentAreaFilled(false);
        DefinitionBtn.setInheritsPopupMenu(true);
        DefinitionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefinitionBtnActionPerformed(evt);
            }
        });
        jPanel1.add(DefinitionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 398, -1));

        ExamplesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExampleBtnDefault.png"))); // NOI18N
        ExamplesBtn.setBorderPainted(false);
        ExamplesBtn.setContentAreaFilled(false);
        ExamplesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamplesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ExamplesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 229, 398, 147));

        ExerciseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExerciseBtnDefault.png"))); // NOI18N
        ExerciseBtn.setBorderPainted(false);
        ExerciseBtn.setContentAreaFilled(false);
        ExerciseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExerciseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ExerciseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 398, -1));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(522, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "maths");
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void DefinitionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefinitionBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "combDefinition");
        }
    }//GEN-LAST:event_DefinitionBtnActionPerformed

    private void ExamplesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamplesBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "combExamples");
        }
    }//GEN-LAST:event_ExamplesBtnActionPerformed

    private void ExerciseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExerciseBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "combExercise");
        }
    }//GEN-LAST:event_ExerciseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DefinitionBtn;
    private javax.swing.JLabel DescriptiveStatistic;
    private javax.swing.JButton ExamplesBtn;
    private javax.swing.JButton ExerciseBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
