
import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class descExercisePanel extends javax.swing.JPanel {
    private ArrayList <DescExercise> dList;
    private double mean, median, mode, range;
    private int count;

    /**
     * Creates new form descExercisePanel
     */
    public descExercisePanel() {
        initComponents();
        //Back Icon changes on hover
        backBtn.setRolloverIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
        backBtn.setSelectedIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
        dList = new ArrayList <>();
        mean = 0.0;
        median = 0.0;
        mode = 0.0;
        range = 0.0;  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DescriptiveStatistic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MeanTf = new javax.swing.JTextField();
        MedianTf = new javax.swing.JTextField();
        ModeTf = new javax.swing.JTextField();
        RangeTf = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DescriptiveStatistic.setBackground(new java.awt.Color(102, 51, 255));
        DescriptiveStatistic.setFont(new java.awt.Font("Tekton Pro", 0, 44)); // NOI18N
        DescriptiveStatistic.setForeground(new java.awt.Color(153, 0, 204));
        DescriptiveStatistic.setText("Descriptive Statistic");
        add(DescriptiveStatistic, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 19, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("1. Find the mean, median, mode, and range for the");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("following list of values:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("13, 18, 13, 14, 13, 16, 14, 21, 13");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mean:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 50, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Median:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 50, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Mode:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Range:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        MeanTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeanTfActionPerformed(evt);
            }
        });
        add(MeanTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 210, -1));

        MedianTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedianTfActionPerformed(evt);
            }
        });
        add(MedianTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 210, -1));
        add(ModeTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 210, -1));
        add(RangeTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 210, -1));

        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/BackBtnDefault.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 523, 100, 80));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\05-04-2015\\重新來過呵呵\\quizApp\\GUIImages\\Statistic\\background.png")); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        //get text from textfields
        mean = Double.parseDouble(MeanTf.getText());
        median = Double.parseDouble(MedianTf.getText());
        mode = Double.parseDouble(ModeTf.getText());
        range = Double.parseDouble(RangeTf.getText());
        
        DescExercise d = new DescExercise();
        d.setMean(mean);
        d.setMedian(median); 
        d.setMode(mode);
        d.setRange(range);
        
        //add object to arraylist
        dList.add(d);
        
        //increment counter
        count++;
        
        for(int i = 0; i < dList.size();i++){
            if(mean==15 && median==14 && mode==13 && range==8){
            JOptionPane.showMessageDialog(null, "You are correct!!");
            }
            else{
            JOptionPane.showMessageDialog(null, "The correct answer is:\n Mean: 15\n Median: 14 \n Mode: 13 \n Range: 8");
            }
        }
        
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void MedianTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedianTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedianTfActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "descriptive");
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void MeanTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeanTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MeanTfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescriptiveStatistic;
    private javax.swing.JTextField MeanTf;
    private javax.swing.JTextField MedianTf;
    private javax.swing.JTextField ModeTf;
    private javax.swing.JTextField RangeTf;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
