/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.CardLayout;
import java.awt.LayoutManager;
import javax.swing.ImageIcon;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Seán
 */
public class mathsPanel extends javax.swing.JPanel {

    /**
     * Creates new form mathsPanel
     */
    public mathsPanel() {
        initComponents();
        //Back Icon changes on hover
        backBtn.setRolloverIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\BackBtnHoverPressed.png"));
        backBtn.setSelectedIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\BackBtnHoverPressed.png"));

        //Check Icon changes on hover
        confirmBtn.setRolloverIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\CheckBtnHoverPressed.png"));
        confirmBtn.setSelectedIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\CheckBtnHoverPressed.png"));

        //ReviewIcon changeson hover
        vennReview.setRolloverIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\reviewIconHoverPressed.png"));
        vennReview.setSelectedIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\reviewIconHoverPressed.png"));

        //VennOption Icon changes on hover
        VennOption.setRolloverIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\setsBtnHoverPressed.png"));
        VennOption.setSelectedIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\setsBtnHoverPressed.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        SetsTitle = new javax.swing.JLabel();
        StatTitle = new javax.swing.JLabel();
        vennReview = new javax.swing.JButton();
        reviewTitle = new javax.swing.JLabel();
        VennOption = new javax.swing.JRadioButton();
        DescOption = new javax.swing.JRadioButton();
        ProbOption = new javax.swing.JRadioButton();
        CombOption = new javax.swing.JRadioButton();
        confirmBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SetsTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        SetsTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/SetsOperationsTitle.png"))); // NOI18N
        jPanel1.add(SetsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        StatTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        StatTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/StatisticsTitle.png"))); // NOI18N
        jPanel1.add(StatTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, 70));

        vennReview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/reviewIcon.png"))); // NOI18N
        vennReview.setToolTipText("Review Understanding");
        vennReview.setContentAreaFilled(false);
        vennReview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vennReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vennReviewActionPerformed(evt);
            }
        });
        jPanel1.add(vennReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 40, 50));

        reviewTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reviewTitle.setForeground(new java.awt.Color(255, 255, 255));
        reviewTitle.setText("Review");
        jPanel1.add(reviewTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 195, -1, 40));

        buttonGroup1.add(VennOption);
        VennOption.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        VennOption.setForeground(new java.awt.Color(255, 255, 255));
        VennOption.setContentAreaFilled(false);
        VennOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VennOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/setsBtnDefault.png"))); // NOI18N
        jPanel1.add(VennOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 390, 80));

        buttonGroup1.add(DescOption);
        DescOption.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        DescOption.setForeground(new java.awt.Color(255, 255, 255));
        DescOption.setText("Descriptive Statistics");
        DescOption.setContentAreaFilled(false);
        DescOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(DescOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 197, -1));

        buttonGroup1.add(ProbOption);
        ProbOption.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ProbOption.setForeground(new java.awt.Color(255, 255, 255));
        ProbOption.setText("Probability");
        ProbOption.setContentAreaFilled(false);
        ProbOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ProbOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        buttonGroup1.add(CombOption);
        CombOption.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CombOption.setForeground(new java.awt.Color(255, 255, 255));
        CombOption.setText("Combinations & Permutations");
        CombOption.setContentAreaFilled(false);
        CombOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(CombOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        confirmBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/CheckBtnDefault.png"))); // NOI18N
        confirmBtn.setContentAreaFilled(false);
        confirmBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });
        jPanel1.add(confirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 100, 80));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/BackBtnDefault.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 100, 80));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/Background.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        if (VennOption.isSelected()) {
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof CardLayout) {
                CardLayout cl = (CardLayout) layout;
                cl.show(getParent(), "vennDiagrams");
            }
        }

        if (DescOption.isSelected()) {
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof CardLayout) {
                CardLayout cl = (CardLayout) layout;
                cl.show(getParent(), "descriptive");
            }
        }

        if (ProbOption.isSelected()) {
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof CardLayout) {
                CardLayout cl = (CardLayout) layout;
                cl.show(getParent(), "probability");
            }
        }

        if (CombOption.isSelected()) {
            LayoutManager layout = getParent().getLayout();
            if (layout instanceof CardLayout) {
                CardLayout cl = (CardLayout) layout;
                cl.show(getParent(), "combination");
            }
        }
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "home");
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void vennReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vennReviewActionPerformed
        // TODO add your handling code here:
        String rate1;
        File f = new File("understanding.txt");

        FileReader fr;
        BufferedReader bReader;

        try {
            fr = new FileReader(f);
            bReader = new BufferedReader(fr);

            rate1 = bReader.readLine();

            JOptionPane.showMessageDialog(null, "It seems that " + rate1);

            bReader.close();
        } catch (IOException ex) {

        }

    }//GEN-LAST:event_vennReviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CombOption;
    private javax.swing.JRadioButton DescOption;
    private javax.swing.JRadioButton ProbOption;
    private javax.swing.JLabel SetsTitle;
    private javax.swing.JLabel StatTitle;
    private javax.swing.JRadioButton VennOption;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel reviewTitle;
    private javax.swing.JButton vennReview;
    // End of variables declaration//GEN-END:variables
}
