
import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.io.File;
import javax.swing.ImageIcon;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Seán
 */
public class photosynthesisPanel extends javax.swing.JPanel {
      
    /**
     * Creates new form photosynthesisPanel
     */
    public photosynthesisPanel() {
        initComponents();
        img1.setVisible(false);
        img2.setVisible(false);
        img3.setVisible(false);
       
       
        //Back Icon changes on hover
        backBtn.setRolloverIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
        backBtn.setSelectedIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photoPanel = new javax.swing.JPanel();
        PhotoLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        miniCloseBtn = new javax.swing.JButton();
        backBtn1 = new javax.swing.JButton();
        photoBackground = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 600));

        photoPanel.setPreferredSize(new java.awt.Dimension(400, 600));
        photoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PhotoLbl.setFont(new java.awt.Font("AR DARLING", 1, 36)); // NOI18N
        PhotoLbl.setForeground(new java.awt.Color(0, 204, 51));
        PhotoLbl.setText("Photosynthesis");
        photoPanel.add(PhotoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/BackBtnDefault.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        photoPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 100, 80));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/one.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        photoPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 50, 80));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/two.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        photoPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 70, 80));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/three.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        photoPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 70, 80));

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 102));
        jLabel2.setText("Labelled Diagrams");
        photoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, 20));

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/img1.png"))); // NOI18N
        photoPanel.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 300, 220));

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/img2.png"))); // NOI18N
        photoPanel.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 320, 80));

        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/img3.png"))); // NOI18N
        photoPanel.add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 160, 410, 200));

        miniCloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/miniCloseBtnDefault.png"))); // NOI18N
        miniCloseBtn.setContentAreaFilled(false);
        miniCloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniCloseBtnActionPerformed(evt);
            }
        });
        photoPanel.add(miniCloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        backBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/miniBackBtnDefault.png"))); // NOI18N
        backBtn1.setContentAreaFilled(false);
        backBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });
        photoPanel.add(backBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        photoBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/background.png"))); // NOI18N
        photoPanel.add(photoBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(photoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(photoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        img1.setVisible(false);
        img2.setVisible(true);
        img3.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "biology");
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        img1.setVisible(true);
        img2.setVisible(false);
        img3.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        img1.setVisible(false);
        img2.setVisible(false);
        img3.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void miniCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniCloseBtnActionPerformed
        // TODO add your handling code here:
        File f = new File("understanding.txt");
        f.delete();

        System.exit(0);
    }//GEN-LAST:event_miniCloseBtnActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "biology");
        }
    }//GEN-LAST:event_backBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PhotoLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn1;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton miniCloseBtn;
    private javax.swing.JLabel photoBackground;
    private javax.swing.JPanel photoPanel;
    // End of variables declaration//GEN-END:variables
}
