
import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class probExercisePanel extends javax.swing.JPanel {
    private ArrayList <ProbExercise> dList;
    private double num, total, prob;
    private int count;
    /**
     * Creates new form probExercisePanel
     */
    public probExercisePanel() {
        initComponents();
        //Back Icon changes on hover
        backBtn.setRolloverIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
        backBtn.setSelectedIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
        
        dList = new ArrayList <>();
        num = 0.0;
        total = 0.0;
        prob = 0.0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        DescriptiveStatistic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TotalTf = new javax.swing.JTextField();
        NumTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ProTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SubmitBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/BackBtnDefault.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 523, 100, 80));

        DescriptiveStatistic.setBackground(new java.awt.Color(102, 51, 255));
        DescriptiveStatistic.setFont(new java.awt.Font("Tekton Pro", 0, 44)); // NOI18N
        DescriptiveStatistic.setForeground(new java.awt.Color(153, 0, 204));
        DescriptiveStatistic.setText("Probability");
        add(DescriptiveStatistic, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("1. Find the chances of rolling a \"4\" with a die.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Total number of outcomes:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, -1));
        add(TotalTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 210, -1));

        NumTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumTfActionPerformed(evt);
            }
        });
        add(NumTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 210, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Number of ways it can happen:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 210, -1));
        add(ProTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 210, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("So the probability is:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, -1));

        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\05-04-2015\\重新來過呵呵\\quizApp\\GUIImages\\Statistic\\background.png")); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();

        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "probability");
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void NumTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTfActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        //get text from textfields
        num = Double.parseDouble(NumTf.getText());
        total = Double.parseDouble(TotalTf.getText());
        prob = Double.parseDouble(ProTf.getText());

        ProbExercise d = new ProbExercise();
        d.setNum(num);
        d.setTotal(total);
        d.setProb(prob);

        //add object to arraylist
        dList.add(d);

        //increment counter
        count++;

        for(int i = 0; i < dList.size();i++){
            if(num==1 && total==6 && prob==0.167){
                JOptionPane.showMessageDialog(null, "You are correct!!");
            }
            else{
                JOptionPane.showMessageDialog(null, "The correct answer is:\n Number of ways it can happen: 1\n Total number of outcomes: 6 \n Probability: 0.167");
            }
        }

    }//GEN-LAST:event_SubmitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescriptiveStatistic;
    private javax.swing.JTextField NumTf;
    private javax.swing.JTextField ProTf;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JTextField TotalTf;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
