/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.CardLayout;
import java.awt.FlowLayout;
import javax.swing.JPanel;

/**
 *
 * @author Amanda
 */
public class quizApp extends javax.swing.JFrame {
    JPanel cardsContainer;
    int scoreCount, failCount;
    String name;
    
    /**
     * Creates new form quizApp
     */
    public quizApp() {
        initComponents();
        quizAppPanel mainCard = new quizAppPanel();
        bioPanel biologyCard = new bioPanel();
        mathsPanel mathsCard = new mathsPanel();
        operationsPanel operationCard = new operationsPanel();
        skelPanel skelCard = new skelPanel();
        photosynthesisPanel photoCard = new photosynthesisPanel();
        vegPanel vegCard = new vegPanel();
        veg2Panel veg2Card = new veg2Panel();
        plantPanel plantCard = new plantPanel();
        respPanel respCard = new respPanel();
        circPanel circCard = new circPanel();
        descPanel descCard = new descPanel();
        descDefinitionPanel descDefinitionCard = new descDefinitionPanel();
        descExamplesPanel descExamplesCard = new descExamplesPanel();
        descExercisePanel descExerciseCard = new descExercisePanel();
        vennPanel vennCard = new vennPanel();
        vennExplanation vennExCard = new vennExplanation();
        vennQuizPanel vennQuizCard = new vennQuizPanel();
        quizOverviewPanel quizOverviewCard = new quizOverviewPanel();
        probPanel probCard = new probPanel();
        probDefinitionPanel probDefinitionCard = new probDefinitionPanel();
        probExamplesPanel probExamplesCard = new probExamplesPanel();
        probExercisePanel probExerciseCard = new probExercisePanel();
        combPanel combCard = new combPanel();
        combDefinitionPanel combDefinitionCard = new combDefinitionPanel();
        combExamplesPanel combExamplesCard = new combExamplesPanel();
        combExercisePanel combExerciseCard = new combExercisePanel();
        
        cardsContainer = new JPanel(new CardLayout());
        cardsContainer.add(mainCard, "home");
        cardsContainer.add(biologyCard,"biology");
        cardsContainer.add(mathsCard, "maths");
        cardsContainer.add(operationCard, "operation");
        cardsContainer.add(skelCard, "skeleton");
        cardsContainer.add(photoCard, "photosynthesis");
        cardsContainer.add(vegCard, "vegetative");
        cardsContainer.add(veg2Card, "vegetative2");
        cardsContainer.add(plantCard, "plant");
        cardsContainer.add(respCard, "respiratory");
        cardsContainer.add(circCard, "circulatory");
        cardsContainer.add(descCard, "descriptive");
        cardsContainer.add(descDefinitionCard, "descDefinition");
        cardsContainer.add(descExamplesCard, "descExamples");
        cardsContainer.add(descExerciseCard, "descExercise");
        cardsContainer.add(vennCard, "vennDiagrams");
        cardsContainer.add(vennExCard, "vennEx");
        cardsContainer.add(vennQuizCard, "vennQuiz");
        cardsContainer.add(quizOverviewCard, "quizOverview");
        cardsContainer.add(probCard, "probability");
        cardsContainer.add(probDefinitionCard, "probDefinition");
        cardsContainer.add(probExamplesCard, "probExamples");
        cardsContainer.add(probExerciseCard, "probExercise");
        cardsContainer.add(combCard, "combination");
        cardsContainer.add(combDefinitionCard, "combDefinition");
        cardsContainer.add(combExamplesCard, "combExamples");
        cardsContainer.add(combExerciseCard, "combExercise");
       
        // add the cards container to the JFrame 
        this.setLayout(new FlowLayout());
        this.add(cardsContainer);
        CardLayout cl = (CardLayout)(cardsContainer.getLayout());
        cl.show(cardsContainer, "home");
    }
    
    public String getName(){
        return name;
    }
    
    public void setName(String name){
        this.name = name;
    }
    
    public int getScoreCount() {
        return scoreCount;
    }
    
     public void setScoreCount(int scoreCount) {
        this.scoreCount = scoreCount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LC Maths & Biology App\n");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quizApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quizApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quizApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quizApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quizApp().setVisible(true);
            }
        });
    }
}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

