
import java.awt.*;
import java.io.File;
import javax.swing.*;
import java.util.*;
import java.io.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Seán
 */
public class quizOverviewPanel extends vennQuizPanel {

    public ArrayList<quizApp> aList;

    /**
     * Creates new form quizOverviewPanel
     */
    public quizOverviewPanel() {
        initComponents();
        aList = new ArrayList<>();
        scoreLbl.setText(String.valueOf(scoreCount));
        failLbl.setText(String.valueOf(failCount));

        //Submit & View Icons change on hover
        addBtn.setRolloverIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\addBtnHoverPressed.png"));
        addBtn.setSelectedIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\addBtnHoverPressed.png"));
        scoreBtn.setRolloverIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\scoreBtnHoverPressed.png"));
        scoreBtn.setSelectedIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\scoreBtnHoverPressed.png"));

        //miniCloseBtn Icon changes on hover
        miniCloseBtn.setRolloverIcon(new ImageIcon("GUIImages\\miniCloseBtnHoverPressed.png"));
        miniCloseBtn.setSelectedIcon(new ImageIcon("GUIImages\\miniCloseBtnHoverPressed.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        miniCloseBtn = new javax.swing.JButton();
        resultTitle = new javax.swing.JLabel();
        failLbl = new javax.swing.JLabel();
        scoreLbl = new javax.swing.JLabel();
        checkIcon = new javax.swing.JLabel();
        failIcon = new javax.swing.JLabel();
        subTitle3 = new javax.swing.JLabel();
        subTitle2 = new javax.swing.JLabel();
        subTitle1 = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        scoreBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        miniCloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/miniCloseBtnDefault.png"))); // NOI18N
        miniCloseBtn.setContentAreaFilled(false);
        miniCloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniCloseBtnActionPerformed(evt);
            }
        });
        add(miniCloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        resultTitle.setFont(new java.awt.Font("Magneto", 1, 48)); // NOI18N
        resultTitle.setForeground(new java.awt.Color(255, 255, 255));
        resultTitle.setText("Result");
        add(resultTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        failLbl.setBackground(new java.awt.Color(255, 255, 255));
        failLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        failLbl.setForeground(new java.awt.Color(255, 255, 255));
        add(failLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, 30));

        scoreLbl.setBackground(new java.awt.Color(255, 255, 255));
        scoreLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        scoreLbl.setForeground(new java.awt.Color(255, 255, 255));
        add(scoreLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, 30));

        checkIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/quizCheck.png"))); // NOI18N
        add(checkIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        failIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/quizFail.png"))); // NOI18N
        add(failIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        subTitle3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        subTitle3.setForeground(new java.awt.Color(255, 255, 255));
        subTitle3.setText("Name");
        add(subTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        subTitle2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subTitle2.setForeground(new java.awt.Color(255, 255, 255));
        subTitle2.setText("Wrong");
        add(subTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        subTitle1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subTitle1.setForeground(new java.awt.Color(255, 255, 255));
        subTitle1.setText("Right");
        add(subTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        subTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        subTitle.setForeground(new java.awt.Color(255, 255, 255));
        subTitle.setText("Out of 5 Questions");
        add(subTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });
        add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 220, -1));

        scoreBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/scoreBtnDefault.png"))); // NOI18N
        scoreBtn.setContentAreaFilled(false);
        scoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreBtnActionPerformed(evt);
            }
        });
        add(scoreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 200, 50));

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/addBtnDefault.png"))); // NOI18N
        addBtn.setActionCommand("");
        addBtn.setContentAreaFilled(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 200, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/Background.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        name = nameTF.getText();

        quizApp a = new quizApp();
        a.setName(name);

        aList.add(a);

        nameTF.setText("");

        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "maths");
        }
        JOptionPane.showMessageDialog(null, "Name saved to ArrayList(Scores are not yet saved or displayed on the Result screen)");
        JOptionPane.showMessageDialog(null, "Repeat quiz to check previous name");

    }//GEN-LAST:event_addBtnActionPerformed

    private void scoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreBtnActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < aList.size(); i++) {
            JOptionPane.showMessageDialog(null, "Name: " + aList.get(i).getName());
        }

    }//GEN-LAST:event_scoreBtnActionPerformed

    private void miniCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniCloseBtnActionPerformed
        // TODO add your handling code here:
        File f = new File("understanding.txt");
        f.delete();

        System.exit(0);
    }//GEN-LAST:event_miniCloseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel background;
    private javax.swing.JLabel checkIcon;
    private javax.swing.JLabel failIcon;
    private javax.swing.JLabel failLbl;
    private javax.swing.JButton miniCloseBtn;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel resultTitle;
    private javax.swing.JButton scoreBtn;
    private javax.swing.JLabel scoreLbl;
    private javax.swing.JLabel subTitle;
    private javax.swing.JLabel subTitle1;
    private javax.swing.JLabel subTitle2;
    private javax.swing.JLabel subTitle3;
    // End of variables declaration//GEN-END:variables
}
