/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.CardLayout;
import java.awt.LayoutManager;
import javax.swing.ImageIcon;
import java.io.*;

/**
 *
 * @author Seán
 */
public class quizAppPanel extends javax.swing.JPanel {

    /**
     * Creates new form quizAppPanel
     */
    public quizAppPanel() {
        initComponents();
        //Maths Icon changes on hover
        mathsBtn.setRolloverIcon(new ImageIcon("GUIImages\\MathsBtnHoverPressed.png"));
        mathsBtn.setSelectedIcon(new ImageIcon("GUIImages\\MathsBtnHoverPressed.png"));

        //Biology Icon changes on hover
        biologyBtn.setRolloverIcon(new ImageIcon("GUIImages\\BiologyBtnHoverPressed.png"));
        biologyBtn.setSelectedIcon(new ImageIcon("GUIImages\\BiologyBtnHoverPressed.png"));

        //Options Icon changes on hover
        optionsBtn.setRolloverIcon(new ImageIcon("GUIImages\\OptionsBtnHoverPressed.png"));
        optionsBtn.setSelectedIcon(new ImageIcon("GUIImages\\OptionsBtnHoverPressed.png"));

        //Close Icon changes on hover
        closeBtn.setRolloverIcon(new ImageIcon("GUIImages\\CloseBtnHoverPressed.png"));
        closeBtn.setSelectedIcon(new ImageIcon("GUIImages\\CloseBtnHoverPressed.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JLabel();
        noOptions = new javax.swing.JLabel();
        footer = new javax.swing.JLabel();
        mathsBtn = new javax.swing.JButton();
        biologyBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        optionsBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setToolTipText(null);
        setMaximumSize(new java.awt.Dimension(400, 550));
        setMinimumSize(new java.awt.Dimension(400, 550));
        setPreferredSize(new java.awt.Dimension(400, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/Banner.png"))); // NOI18N
        add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        noOptions.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        noOptions.setForeground(new java.awt.Color(255, 255, 255));
        noOptions.setText("No options available yet");
        add(noOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, -1));
        noOptions.setVisible(false);

        footer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/Footer.png"))); // NOI18N
        add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, -1));

        mathsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/MathsBtnDefault.png"))); // NOI18N
        mathsBtn.setContentAreaFilled(false);
        mathsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mathsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathsBtnActionPerformed(evt);
            }
        });
        add(mathsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 400, 160));

        biologyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/BiologyBtnDefault.png"))); // NOI18N
        biologyBtn.setContentAreaFilled(false);
        biologyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        biologyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biologyBtnActionPerformed(evt);
            }
        });
        add(biologyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 400, 150));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/CloseBtnDefault.png"))); // NOI18N
        closeBtn.setContentAreaFilled(false);
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 200, 160));

        optionsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/OptionsBtn.png"))); // NOI18N
        optionsBtn.setContentAreaFilled(false);
        optionsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        optionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsBtnActionPerformed(evt);
            }
        });
        add(optionsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 200, 160));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Seán\\Documents\\quizApp\\GUIImages\\Background.png")); // NOI18N
        background.setToolTipText(null);
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
        //Navigates to Maths Section
    private void mathsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathsBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "maths");
        }
    }//GEN-LAST:event_mathsBtnActionPerformed
    //Navigates to Biology Section
    private void biologyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biologyBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "biology");
        }
    }//GEN-LAST:event_biologyBtnActionPerformed
    //Closes the application
    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        File f = new File("understanding.txt");
        f.delete();

        System.exit(0);
    }//GEN-LAST:event_closeBtnActionPerformed
    //Potential Options menu for button sounds etc. 
    private void optionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsBtnActionPerformed
        // TODO add your handling code here:
        noOptions.setVisible(true);
    }//GEN-LAST:event_optionsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel banner;
    private javax.swing.JButton biologyBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel footer;
    private javax.swing.JButton mathsBtn;
    private javax.swing.JLabel noOptions;
    private javax.swing.JButton optionsBtn;
    // End of variables declaration//GEN-END:variables

    private void setResizable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
