
import java.awt.CardLayout;
import java.awt.LayoutManager;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Renalyn
 */
public class respPanel extends javax.swing.JPanel {

    /**
     * Creates new form respPanel
     */
    public respPanel() {
        initComponents();
        lungs1Img.setVisible(false);
        alveoliImg.setVisible(false);
        alveoli1Img.setVisible(false);
        alveoli2Img.setVisible(false);
        
        //Back Icon changes on hover
        backBtn.setRolloverIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
        backBtn.setSelectedIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alveoli2Img = new javax.swing.JLabel();
        alveoli1Img = new javax.swing.JLabel();
        alveoliImg = new javax.swing.JLabel();
        lungs1Img = new javax.swing.JLabel();
        lungsImg = new javax.swing.JLabel();
        diagramLbl = new javax.swing.JLabel();
        respLbl1 = new javax.swing.JLabel();
        diagram1 = new javax.swing.JButton();
        diagram2 = new javax.swing.JButton();
        diagram3 = new javax.swing.JButton();
        diagram4 = new javax.swing.JButton();
        diagram5 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alveoli2Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/alveoli2.jpg"))); // NOI18N
        add(alveoli2Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 210));

        alveoli1Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/alveoli1.jpg"))); // NOI18N
        add(alveoli1Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 210));

        alveoliImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/alveoli.jpg"))); // NOI18N
        add(alveoliImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 270));

        lungs1Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/lungs1.jpg"))); // NOI18N
        add(lungs1Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        lungsImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/lungs.jpg"))); // NOI18N
        add(lungsImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 370));

        diagramLbl.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        diagramLbl.setText("Diagram:");
        add(diagramLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 60, 19));

        respLbl1.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        respLbl1.setText("Respiratory System");
        add(respLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        diagram1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/num1.png"))); // NOI18N
        diagram1.setContentAreaFilled(false);
        diagram1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagram1ActionPerformed(evt);
            }
        });
        add(diagram1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 40, -1));

        diagram2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/num3.png"))); // NOI18N
        diagram2.setContentAreaFilled(false);
        diagram2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagram2ActionPerformed(evt);
            }
        });
        add(diagram2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 40, -1));

        diagram3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/num4.png"))); // NOI18N
        diagram3.setContentAreaFilled(false);
        diagram3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagram3ActionPerformed(evt);
            }
        });
        add(diagram3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 40, -1));

        diagram4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/num5.png"))); // NOI18N
        diagram4.setContentAreaFilled(false);
        diagram4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagram4ActionPerformed(evt);
            }
        });
        add(diagram4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 40, -1));

        diagram5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/num2.png"))); // NOI18N
        diagram5.setContentAreaFilled(false);
        diagram5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagram5ActionPerformed(evt);
            }
        });
        add(diagram5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 40, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/BackBtnDefault.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 100, 80));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/bioBg.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void diagram1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagram1ActionPerformed
        lungsImg.setVisible(true);
        lungs1Img.setVisible(false);
        alveoliImg.setVisible(false);
        alveoli1Img.setVisible(false);
        alveoli2Img.setVisible(false);
    }//GEN-LAST:event_diagram1ActionPerformed

    private void diagram2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagram2ActionPerformed
        lungsImg.setVisible(false);
        lungs1Img.setVisible(false);
        alveoliImg.setVisible(true);
        alveoli1Img.setVisible(false);
        alveoli2Img.setVisible(false);
    }//GEN-LAST:event_diagram2ActionPerformed

    private void diagram3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagram3ActionPerformed
        lungsImg.setVisible(false);
        lungs1Img.setVisible(false);
        alveoliImg.setVisible(false);
        alveoli1Img.setVisible(true);
        alveoli2Img.setVisible(false);
    }//GEN-LAST:event_diagram3ActionPerformed

    private void diagram4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagram4ActionPerformed
        lungsImg.setVisible(false);
        lungs1Img.setVisible(false);
        alveoliImg.setVisible(false);
        alveoli1Img.setVisible(false);
        alveoli2Img.setVisible(true);
    }//GEN-LAST:event_diagram4ActionPerformed

    private void diagram5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagram5ActionPerformed
        lungsImg.setVisible(false);
        lungs1Img.setVisible(true);
        alveoliImg.setVisible(false);
        alveoli1Img.setVisible(false);
        alveoli2Img.setVisible(false);
    }//GEN-LAST:event_diagram5ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "biology");
        }
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alveoli1Img;
    private javax.swing.JLabel alveoli2Img;
    private javax.swing.JLabel alveoliImg;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel background;
    private javax.swing.JButton diagram1;
    private javax.swing.JButton diagram2;
    private javax.swing.JButton diagram3;
    private javax.swing.JButton diagram4;
    private javax.swing.JButton diagram5;
    private javax.swing.JLabel diagramLbl;
    private javax.swing.JLabel lungs1Img;
    private javax.swing.JLabel lungsImg;
    private javax.swing.JLabel respLbl1;
    // End of variables declaration//GEN-END:variables
}
