
import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Seán
 */
public class skelPanel extends javax.swing.JPanel {
        private final ArrayList <skeletonJava> aList;
        private String Question;
        private int count;
    /**
     * Creates new form skelPanel
     */
    public skelPanel() {
        initComponents();
       aList = new ArrayList <>();
       Question = new String();
       count = 0; 
        
        //Back Icon changes on hover
        backBtn.setRolloverIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
        backBtn.setSelectedIcon(new ImageIcon("GUIImages\\BiologyPanelGUI\\BackBtnHoverPressed.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        Lbl = new javax.swing.JLabel();
        SetsLbl = new javax.swing.JLabel();
        quesLbl = new javax.swing.JLabel();
        addQues = new javax.swing.JButton();
        viewQues = new javax.swing.JButton();
        delQues = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        question = new javax.swing.JTextField();
        num1 = new javax.swing.JLabel();
        num2 = new javax.swing.JLabel();
        num3 = new javax.swing.JLabel();
        num4 = new javax.swing.JLabel();
        Lbl1 = new javax.swing.JLabel();
        Lbl2 = new javax.swing.JLabel();
        Lbl3 = new javax.swing.JLabel();
        Lbl4 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 600));

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        Lbl.setText("Create your own questions for revision!");
        jPanel2.add(Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        SetsLbl.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        SetsLbl.setText("Skeletal System");
        jPanel2.add(SetsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        quesLbl.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 20)); // NOI18N
        quesLbl.setText("Enter Question:");
        jPanel2.add(quesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 20));

        addQues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/add.png"))); // NOI18N
        addQues.setContentAreaFilled(false);
        addQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuesActionPerformed(evt);
            }
        });
        jPanel2.add(addQues, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        viewQues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/view.png"))); // NOI18N
        viewQues.setContentAreaFilled(false);
        viewQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewQuesActionPerformed(evt);
            }
        });
        jPanel2.add(viewQues, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        delQues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/delete.png"))); // NOI18N
        delQues.setContentAreaFilled(false);
        delQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delQuesActionPerformed(evt);
            }
        });
        jPanel2.add(delQues, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/BackBtnDefault.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel2.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 100, 80));
        jPanel2.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 210, -1));

        num1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/1.png"))); // NOI18N
        jPanel2.add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        num2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/2.png"))); // NOI18N
        jPanel2.add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        num3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/3.png"))); // NOI18N
        jPanel2.add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        num4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/4.png"))); // NOI18N
        jPanel2.add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        Lbl1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        Lbl1.setText("Enter your question ");
        jPanel2.add(Lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        Lbl2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        Lbl2.setText("Click the add button to save it");
        jPanel2.add(Lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        Lbl3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        Lbl3.setText("Click the document to view it");
        jPanel2.add(Lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        Lbl4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        Lbl4.setText("Click the rubbish bin to delete it");
        jPanel2.add(Lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/bioBg.png"))); // NOI18N
        jPanel2.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "biology");
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void viewQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewQuesActionPerformed
            for (skeletonJava aList1 : aList) {
                JOptionPane.showMessageDialog(null, "Question: " + aList1.getQuestion());
            }
    }//GEN-LAST:event_viewQuesActionPerformed

    private void delQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delQuesActionPerformed
        // TODO add your handling code here:
        if(question.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter a question please!");
        }
        else if(count ==0){
            JOptionPane.showMessageDialog(null,"No items to be deleted!");
        }
        else{
            Question = question.getText();
            
            for(int i = 0; i < aList.size();i++){
                if(aList.get(i).getQuestion().equals(Question)){
                    aList.remove(i);
                    count = count - 1;
                    JOptionPane.showMessageDialog(null,"Question at index "+ i + " is deleted!");
                    break;
                }
                if(i==count-1){
                    JOptionPane.showMessageDialog(null,"No item found!");
                }
            }
        }
    }//GEN-LAST:event_delQuesActionPerformed

    private void addQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuesActionPerformed
        // TODO add your handling code here:
        Question = question.getText();

        skeletonJava a = new skeletonJava();
        a.setQuestion(Question);

        aList.add(a);

        count++;
    }//GEN-LAST:event_addQuesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl;
    private javax.swing.JLabel Lbl1;
    private javax.swing.JLabel Lbl2;
    private javax.swing.JLabel Lbl3;
    private javax.swing.JLabel Lbl4;
    private javax.swing.JLabel SetsLbl;
    private javax.swing.JButton addQues;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delQues;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel num3;
    private javax.swing.JLabel num4;
    private javax.swing.JLabel quesLbl;
    private javax.swing.JTextField question;
    private javax.swing.JButton viewQues;
    // End of variables declaration//GEN-END:variables
}
