
import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.io.File;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Renalyn
 */
public class vegPanel extends javax.swing.JPanel {

    /**
     * Creates new form vegPanel
     */
    public vegPanel() {
        initComponents();
       
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vegLbl = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextArea2 = new javax.swing.JTextArea();
        vegImg = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        backBtn1 = new javax.swing.JButton();
        miniCloseBtn = new javax.swing.JButton();
        vegBackground = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vegLbl.setFont(new java.awt.Font("AR DESTINE", 1, 24)); // NOI18N
        vegLbl.setForeground(new java.awt.Color(204, 0, 0));
        vegLbl.setText("Vegetative Propagation");
        add(vegLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Vegetative Propagation\nA form of asexual reproduction of a plant. Only one \nplant is involved and the offspring  is the result of \none parent. The new plant is genetically identical to \nthe parent.");
        jTextArea1.setOpaque(false);
        add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 161, 346, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea2.setRows(5);
        jTextArea2.setText("Stem Runners\nStems that grow horizontally above the ground. They \nhave nodes where buds are formed.\nThese buds grow into a new plant.");
        jTextArea2.setOpaque(false);
        add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 320, -1));

        vegImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/propagation.jpeg"))); // NOI18N
        add(vegImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 350, 260));

        nextBtn.setBackground(new java.awt.Color(153, 153, 153));
        nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/arrowNext.png"))); // NOI18N
        nextBtn.setContentAreaFilled(false);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 80, 60));

        backBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/miniBackBtnDefault.png"))); // NOI18N
        backBtn1.setContentAreaFilled(false);
        backBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });
        add(backBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        miniCloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/miniCloseBtnDefault.png"))); // NOI18N
        miniCloseBtn.setContentAreaFilled(false);
        miniCloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniCloseBtnActionPerformed(evt);
            }
        });
        add(miniCloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        vegBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/background.png"))); // NOI18N
        add(vegBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        //to go to next page
       LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "vegetative2");
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "biology");
        }
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void miniCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniCloseBtnActionPerformed
        // TODO add your handling code here:
        File f = new File("understanding.txt");
        f.delete();

        System.exit(0);
    }//GEN-LAST:event_miniCloseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton miniCloseBtn;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel vegBackground;
    private javax.swing.JLabel vegImg;
    private javax.swing.JLabel vegLbl;
    // End of variables declaration//GEN-END:variables
}
