
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Seán
 */
public class vennExplanation extends javax.swing.JPanel implements ActionListener {

    File f = new File("understanding.txt");
    String quizPass = "SetOperQuiz";

    /**
     * Creates new form vennExplanation
     */
    public vennExplanation() {
        initComponents();
        //rateBtn1 Icon changes on hover
        rateBtn1.setRolloverIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\rateBtn1HoverPressed.png"));
        rateBtn1.setSelectedIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\rateBtn1HoverPressed.png"));

        //rateBtn2 Icon changes on hover
        rateBtn2.setRolloverIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\rateBtn2HoverPressed.png"));
        rateBtn2.setSelectedIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\rateBtn2HoverPressed.png"));

        //rateBtn3 Icon changes on hover
        rateBtn3.setRolloverIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\rateBtn3HoverPressed.png"));
        rateBtn3.setSelectedIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\rateBtn3HoverPressed.png"));

        //rateBtn4 Icon changes on hover
        rateBtn4.setRolloverIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\rateBtn4HoverPressed.png"));
        rateBtn4.setSelectedIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\rateBtn4HoverPressed.png"));

        //rateBtn5 Icon changes on hover
        rateBtn5.setRolloverIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\rateBtn5HoverPressed.png"));
        rateBtn5.setSelectedIcon(new ImageIcon("GUIImages\\MathsPanelGUI\\rateBtn5HoverPressed.png"));

        //Back Icon changes on hover
        backBtn.setRolloverIcon(new ImageIcon("GUIImages\\miniBackBtnHoverPressed.png"));
        backBtn.setSelectedIcon(new ImageIcon("GUIImages\\miniBackBtnHoverPressed.png"));

        //miniCloseBtn Icon changes on hover
        miniCloseBtn.setRolloverIcon(new ImageIcon("GUIImages\\miniCloseBtnHoverPressed.png"));
        miniCloseBtn.setSelectedIcon(new ImageIcon("GUIImages\\miniCloseBtnHoverPressed.png"));

        timerTest.setVisible(false);

        //Diagram startup visibilities
        vennDiagramA.setVisible(false);
        areaA.setVisible(false);
        vennDiagramAnC.setVisible(false);
        areaAnC.setVisible(false);
        vennDiagramAuC.setVisible(false);
        areaAuC.setVisible(false);
        vennDiagramAdiffC.setVisible(false);
        areaAdiffC.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        miniCloseBtn = new javax.swing.JButton();
        vennExBanner = new javax.swing.JLabel();
        exAreaBanner = new javax.swing.JLabel();
        titleBottom = new javax.swing.JLabel();
        exAreaBottom = new javax.swing.JLabel();
        selectTitle = new javax.swing.JLabel();
        vennDiagramAdiffC = new javax.swing.JLabel();
        vennDiagramAuC = new javax.swing.JLabel();
        vennDiagramAnC = new javax.swing.JLabel();
        vennDiagramA = new javax.swing.JLabel();
        vennDiagram = new javax.swing.JLabel();
        AdiffC = new javax.swing.JButton();
        AuC = new javax.swing.JButton();
        AnC = new javax.swing.JButton();
        A = new javax.swing.JButton();
        areaAdiffC = new javax.swing.JTextArea();
        areaAuC = new javax.swing.JTextArea();
        areaAnC = new javax.swing.JTextArea();
        areaA = new javax.swing.JTextArea();
        blankArea = new javax.swing.JTextArea();
        rateBtn5 = new javax.swing.JButton();
        rateBtn4 = new javax.swing.JButton();
        rateBtn3 = new javax.swing.JButton();
        rateBtn2 = new javax.swing.JButton();
        rateBtn1 = new javax.swing.JButton();
        timerTest = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(400, 600));
        setPreferredSize(new java.awt.Dimension(400, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/miniBackBtnDefault.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        miniCloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/miniCloseBtnDefault.png"))); // NOI18N
        miniCloseBtn.setContentAreaFilled(false);
        miniCloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniCloseBtnActionPerformed(evt);
            }
        });
        add(miniCloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        vennExBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/venExBanner.png"))); // NOI18N
        add(vennExBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        exAreaBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/exAreaBanner.png"))); // NOI18N
        add(exAreaBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        titleBottom.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        titleBottom.setForeground(new java.awt.Color(255, 255, 255));
        titleBottom.setText("How well do you understand?");
        add(titleBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, -1, 40));

        exAreaBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/exAreaBottom.png"))); // NOI18N
        add(exAreaBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        selectTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        selectTitle.setForeground(new java.awt.Color(255, 255, 255));
        selectTitle.setText("Click the Operations:");
        add(selectTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        vennDiagramAdiffC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/vennDiagramAdiffC.png"))); // NOI18N
        add(vennDiagramAdiffC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        vennDiagramAuC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/vennDiagramAuC.png"))); // NOI18N
        add(vennDiagramAuC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        vennDiagramAnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/vennDiagramAnC.png"))); // NOI18N
        add(vennDiagramAnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        vennDiagramA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/vennDiagramA.png"))); // NOI18N
        add(vennDiagramA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        vennDiagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/vennDiagramDefault.png"))); // NOI18N
        add(vennDiagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        AdiffC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AdiffC.setForeground(new java.awt.Color(255, 255, 255));
        AdiffC.setText("A -  C");
        AdiffC.setContentAreaFilled(false);
        AdiffC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdiffC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdiffCActionPerformed(evt);
            }
        });
        add(AdiffC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 20));

        AuC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AuC.setForeground(new java.awt.Color(255, 255, 255));
        AuC.setText("A u C");
        AuC.setContentAreaFilled(false);
        AuC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AuC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuCActionPerformed(evt);
            }
        });
        add(AuC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        AnC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AnC.setForeground(new java.awt.Color(255, 255, 255));
        AnC.setText("A n C");
        AnC.setContentAreaFilled(false);
        AnC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnCActionPerformed(evt);
            }
        });
        add(AnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        A.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        A.setForeground(new java.awt.Color(255, 255, 255));
        A.setText("A");
        A.setContentAreaFilled(false);
        A.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        areaAdiffC.setEditable(false);
        areaAdiffC.setColumns(20);
        areaAdiffC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        areaAdiffC.setRows(5);
        areaAdiffC.setText("The difference of sets A from C , denoted by A - C , \nis the set defined as:\n\n             A - C = { x | x  A  x  B } \n\nWhat this is looking for is all of the elements in Set A \nthat aren't in set C.");
        areaAdiffC.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        add(areaAdiffC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 274, 400, 230));

        areaAuC.setEditable(false);
        areaAuC.setColumns(20);
        areaAuC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        areaAuC.setRows(5);
        areaAuC.setText("A u C (u = Union) contains all of the elements within \nboth sets, including their intersection. An element of \nA u C is required to belong to at least one of these sets.");
        areaAuC.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        add(areaAuC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 274, 400, 230));

        areaAnC.setEditable(false);
        areaAnC.setColumns(20);
        areaAnC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        areaAnC.setRows(5);
        areaAnC.setText("Elements of A n C (n = Intersection) refer to the \nelements belonging to both sets in tandem, \nthe ones that they both share.\nThis is represented by the darkened red 'intersection' \nbetween both sets.");
        areaAnC.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        add(areaAnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 274, 400, 230));

        areaA.setEditable(false);
        areaA.setColumns(20);
        areaA.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        areaA.setRows(5);
        areaA.setText("All elements belonging to the Set A, \nrepresented by the entire green circle \non the Venn Diagram. \nBy 'all', we include even those elements \nwhich are also included in other sets.\nThe same applies for B & C in their respective cases.");
        areaA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        add(areaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 274, 400, 230));

        blankArea.setEditable(false);
        blankArea.setColumns(20);
        blankArea.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        blankArea.setRows(5);
        blankArea.setText("Sets can be combined in a number of \ndifferent ways to produce another set.\n\nThe clickable basic operations above will \nintoduce their properties and meanings, \nbest represented on Venn Diagrams \n(Visual representation of Sets).");
        add(blankArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 274, 400, 230));

        rateBtn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/rateBtn5Default.png"))); // NOI18N
        rateBtn5.setContentAreaFilled(false);
        rateBtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rateBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateBtn5ActionPerformed(evt);
            }
        });
        add(rateBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 80, 80));

        rateBtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/rateBtn4Default.png"))); // NOI18N
        rateBtn4.setContentAreaFilled(false);
        rateBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rateBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateBtn4ActionPerformed(evt);
            }
        });
        add(rateBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 80, 80));

        rateBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/rateBtn3Default.png"))); // NOI18N
        rateBtn3.setContentAreaFilled(false);
        rateBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rateBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateBtn3ActionPerformed(evt);
            }
        });
        add(rateBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 80, 80));

        rateBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/rateBtn2Default.png"))); // NOI18N
        rateBtn2.setContentAreaFilled(false);
        rateBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rateBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateBtn2ActionPerformed(evt);
            }
        });
        add(rateBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 80, 80));

        rateBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/rateBtn1Default.png"))); // NOI18N
        rateBtn1.setContentAreaFilled(false);
        rateBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateBtn1ActionPerformed(evt);
            }
        });
        add(rateBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 80, 80));
        add(timerTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/background2.png"))); // NOI18N
        add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateBtn1ActionPerformed
        // TODO add your handling code here:
        String rate1 = "you don't understand, further study is required";

        FileWriter fw;
        BufferedWriter bWriter;

        try {
            fw = new FileWriter(f);
            bWriter = new BufferedWriter(fw);

            bWriter.write(rate1);
            bWriter.newLine();

            bWriter.close();

            JOptionPane.showMessageDialog(null, "Understanding written to file" + f + ", check review to see this");
        } catch (IOException ex) {
            System.out.println(ex.toString() + "Error writting to file");
        }

        //Reset Visibilities
        vennDiagram.setVisible(true);
        blankArea.setVisible(true);
        vennDiagramA.setVisible(false);
        areaA.setVisible(false);
        vennDiagramAnC.setVisible(false);
        areaAnC.setVisible(false);
        vennDiagramAuC.setVisible(false);
        areaAuC.setVisible(false);
        vennDiagramAdiffC.setVisible(false);
        areaAdiffC.setVisible(false);

        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "maths");
        }
    }//GEN-LAST:event_rateBtn1ActionPerformed

    private void rateBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateBtn2ActionPerformed
        // TODO add your handling code here:
        String rate1 = "you understand some";

        FileWriter fw;
        BufferedWriter bWriter;

        try {
            fw = new FileWriter(f);
            bWriter = new BufferedWriter(fw);

            bWriter.write(rate1);
            bWriter.newLine();

            bWriter.close();

            JOptionPane.showMessageDialog(null, "Understanding written to file" + f + ", check review to see this");
        } catch (IOException ex) {
            System.out.println(ex.toString() + "Error writting to file");
        }

        //Reset Visibilities
        vennDiagram.setVisible(true);
        blankArea.setVisible(true);
        vennDiagramA.setVisible(false);
        areaA.setVisible(false);
        vennDiagramAnC.setVisible(false);
        areaAnC.setVisible(false);
        vennDiagramAuC.setVisible(false);
        areaAuC.setVisible(false);
        vennDiagramAdiffC.setVisible(false);
        areaAdiffC.setVisible(false);

        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "maths");
        }
    }//GEN-LAST:event_rateBtn2ActionPerformed

    private void rateBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateBtn3ActionPerformed
        // TODO add your handling code here:
        String rate1 = "you've grasped a balanced understanding";

        FileWriter fw;
        BufferedWriter bWriter;

        try {
            fw = new FileWriter(f);
            bWriter = new BufferedWriter(fw);

            bWriter.write(rate1);
            bWriter.newLine();

            bWriter.close();

            JOptionPane.showMessageDialog(null, "Understanding written to file" + f + ", check review to see this");
        } catch (IOException ex) {
            System.out.println(ex.toString() + "Error writting to file");
        }

        //Reset Visibilities
        vennDiagram.setVisible(true);
        blankArea.setVisible(true);
        vennDiagramA.setVisible(false);
        areaA.setVisible(false);
        vennDiagramAnC.setVisible(false);
        areaAnC.setVisible(false);
        vennDiagramAuC.setVisible(false);
        areaAuC.setVisible(false);
        vennDiagramAdiffC.setVisible(false);
        areaAdiffC.setVisible(false);

        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "maths");
        }
    }//GEN-LAST:event_rateBtn3ActionPerformed

    private void rateBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateBtn4ActionPerformed
        // TODO add your handling code here:
        String rate1 = "you're close to fully understanding Sets/Venn Diagrams!";

        FileWriter fw;
        BufferedWriter bWriter;

        try {
            fw = new FileWriter(f);
            bWriter = new BufferedWriter(fw);

            bWriter.write(rate1);
            bWriter.newLine();

            bWriter.close();

            JOptionPane.showMessageDialog(null, "Understanding written to file" + f + ", check review to see this");
        } catch (IOException ex) {
            System.out.println(ex.toString() + "Error writting to file");
        }

        //Reset Visibilities
        vennDiagram.setVisible(true);
        blankArea.setVisible(true);
        vennDiagramA.setVisible(false);
        areaA.setVisible(false);
        vennDiagramAnC.setVisible(false);
        areaAnC.setVisible(false);
        vennDiagramAuC.setVisible(false);
        areaAuC.setVisible(false);
        vennDiagramAdiffC.setVisible(false);
        areaAdiffC.setVisible(false);

        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "maths");
        }
    }//GEN-LAST:event_rateBtn4ActionPerformed

    private void rateBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateBtn5ActionPerformed
        // TODO add your handling code here:
        String rate1 = "you understand the entirety of the subject, the quiz password is: " + quizPass;

        FileWriter fw;
        BufferedWriter bWriter;

        try {
            fw = new FileWriter(f);
            bWriter = new BufferedWriter(fw);

            bWriter.write(rate1);
            bWriter.newLine();

            bWriter.close();

            JOptionPane.showMessageDialog(null, "Understanding written to file" + f + ", check review to see this");
            JOptionPane.showMessageDialog(null, "It seems that " + rate1);
        } catch (IOException ex) {
            System.out.println(ex.toString() + "Error writting to file");
        }

        //Reset Visibilities
        vennDiagram.setVisible(true);
        blankArea.setVisible(true);
        vennDiagramA.setVisible(false);
        areaA.setVisible(false);
        vennDiagramAnC.setVisible(false);
        areaAnC.setVisible(false);
        vennDiagramAuC.setVisible(false);
        areaAuC.setVisible(false);
        vennDiagramAdiffC.setVisible(false);
        areaAdiffC.setVisible(false);

        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "maths");
        }
    }//GEN-LAST:event_rateBtn5ActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
        vennDiagram.setVisible(false);
        vennDiagramA.setVisible(true);
        areaA.setVisible(true);
        areaAnC.setVisible(false);
        vennDiagramAnC.setVisible(false);
        vennDiagramAuC.setVisible(false);
        areaAuC.setVisible(false);
        vennDiagramAdiffC.setVisible(false);
        areaAdiffC.setVisible(false);
    }//GEN-LAST:event_AActionPerformed

    private void AnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnCActionPerformed
        // TODO add your handling code here:
        vennDiagram.setVisible(false);
        vennDiagramA.setVisible(false);
        areaA.setVisible(false);
        areaAnC.setVisible(true);
        vennDiagramAnC.setVisible(true);
        vennDiagramAuC.setVisible(false);
        areaAuC.setVisible(false);
        vennDiagramAdiffC.setVisible(false);
        areaAdiffC.setVisible(false);
    }//GEN-LAST:event_AnCActionPerformed

    private void miniCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniCloseBtnActionPerformed
        // TODO add your handling code here:
        File f = new File("understanding.txt");
        f.delete();

        System.exit(0);
    }//GEN-LAST:event_miniCloseBtnActionPerformed

    private void AuCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuCActionPerformed
        // TODO add your handling code here:
        vennDiagram.setVisible(false);
        vennDiagramA.setVisible(false);
        areaA.setVisible(false);
        areaAnC.setVisible(false);
        vennDiagramAnC.setVisible(false);
        vennDiagramAuC.setVisible(true);
        areaAuC.setVisible(true);
        vennDiagramAdiffC.setVisible(false);
        areaAdiffC.setVisible(false);
    }//GEN-LAST:event_AuCActionPerformed

    private void AdiffCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdiffCActionPerformed
        // TODO add your handling code here:
        vennDiagram.setVisible(false);
        vennDiagramA.setVisible(false);
        areaA.setVisible(false);
        areaAnC.setVisible(false);
        vennDiagramAnC.setVisible(false);
        vennDiagramAuC.setVisible(false);
        areaAuC.setVisible(false);
        vennDiagramAdiffC.setVisible(true);
        areaAdiffC.setVisible(true);
    }//GEN-LAST:event_AdiffCActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        //Reset Visibilities
        vennDiagram.setVisible(true);
        blankArea.setVisible(true);
        vennDiagramA.setVisible(false);
        areaA.setVisible(false);
        vennDiagramAnC.setVisible(false);
        areaAnC.setVisible(false);
        vennDiagramAuC.setVisible(false);
        areaAuC.setVisible(false);
        vennDiagramAdiffC.setVisible(false);
        areaAdiffC.setVisible(false);

        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "vennDiagrams");
        }

    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton AdiffC;
    private javax.swing.JButton AnC;
    private javax.swing.JButton AuC;
    private javax.swing.JTextArea areaA;
    private javax.swing.JTextArea areaAdiffC;
    private javax.swing.JTextArea areaAnC;
    private javax.swing.JTextArea areaAuC;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel background2;
    private javax.swing.JTextArea blankArea;
    private javax.swing.JLabel exAreaBanner;
    private javax.swing.JLabel exAreaBottom;
    private javax.swing.JButton miniCloseBtn;
    private javax.swing.JButton rateBtn1;
    private javax.swing.JButton rateBtn2;
    private javax.swing.JButton rateBtn3;
    private javax.swing.JButton rateBtn4;
    private javax.swing.JButton rateBtn5;
    private javax.swing.JLabel selectTitle;
    private javax.swing.JLabel timerTest;
    private javax.swing.JLabel titleBottom;
    private javax.swing.JLabel vennDiagram;
    private javax.swing.JLabel vennDiagramA;
    private javax.swing.JLabel vennDiagramAdiffC;
    private javax.swing.JLabel vennDiagramAnC;
    private javax.swing.JLabel vennDiagramAuC;
    private javax.swing.JLabel vennExBanner;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
